theme: jekyll-theme-slate
title: openEQUELLA
description: A digital repository providing a single platform to house your teaching and learning, research, media, and library content.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: equella
  card: summary
